#ifndef _ZSCENEENTRYSTATE_H_
#define _ZSCENEENTRYSTATE_H_

#define	CASESTATE(x)	case CMD::x:

#define NEED_SEND_TO_NINE_STATE		\
	CASESTATE(USTATE_DEATH)	\
	CASESTATE(USTATE_POISON)	\
	CASESTATE(USTATE_FREEZE)	\
	CASESTATE(USTATE_WAR)	\
	CASESTATE(USTATE_CRAZY)	\
	CASESTATE(USTATE_ROCK)	\
	CASESTATE(USTATE_CONFUSION)	\
	CASESTATE(USTATE_PALSY)	\
	CASESTATE(USTATE_REVERT)	\
	CASESTATE(USTATE_GAMEMSTER)	\
	CASESTATE(USTATE_BUSINESSTASK)	\
	CASESTATE(USTATE_LZ_FANGHUDUN)	\
	CASESTATE(USTATE_LZ_GAOSHEPAO)	\
	CASESTATE(USTATE_TMTASK)	\
	CASESTATE(USTATE_LZ_WUQI)	\
	CASESTATE(USTATE_LZ_XUANFENG)	\
	CASESTATE(USTATE_LZ_YULEI)	\
	CASESTATE(USTATE_LZ_RE)	\
	CASESTATE(USTATE_LZ_SHAYU)	\
	CASESTATE(USTATE_RELIVEWEAK)	\
	CASESTATE(USTATE_RELIVERING)	\
	CASESTATE(USTATE_LZ_MEIRENYU)	\
	CASESTATE(USTATE_MINGYUN)	\
	CASESTATE(USTATE_MINDWEAK)	\
	CASESTATE(USTATE_ROSE)	\
	CASESTATE(USTATE_TOWER)	\
	CASESTATE(USTATE_FACEOFF)	\
	CASESTATE(USTATE_START_QUEST)	\
	CASESTATE(USTATE_DOING_QUEST)	\
	CASESTATE(USTATE_FINISH_QUEST)	\
	CASESTATE(USTATE_TIZHIJIAQIANG)	\
	CASESTATE(USTATE_RIDE)	\
	CASESTATE(USTATE_JIANZAOZHUANGTAI)	\
	CASESTATE(USTATE_POWERDEF)	\
	CASESTATE(ZHANLINGZONGDUO)	\
	CASESTATE(USTATE_LONGZHOUGUANGMANG)	\
	CASESTATE(USTATE_ACCRTSKILL)	\
	CASESTATE(USTATE_DEATHHURT)	\
	CASESTATE(USTATE_CHANGEFACE)	\
	CASESTATE(USTATE_DIAMONDMAGIC)	\
	CASESTATE(USTATE_GODBLESS)	\
	CASESTATE(USTATE_LOSTSPRITE)	\
	CASESTATE(USTATE_SITDOWN)	\
	CASESTATE(USTATE_HURT_ABSTRACT)	\
	CASESTATE(USTATE_BOMB_ATTACK)	\
	CASESTATE(USTATE_MAGIC_DEFENCE)	\
	CASESTATE(USTATE_PK)	\
	CASESTATE(USTATE_GOD_GIVE_SOUND)	\
	CASESTATE(USTATE_WIND_SKILL)	\
	CASESTATE(USTATE_FIGHT_TO_DEFENCE)	\
	CASESTATE(USTATE_DEFENCE_TO_FIGHT)	\
	CASESTATE(USTATE_CAREFUL_LOOKAT)	\
	CASESTATE(USTATE_MAGIC_SKILL_MASTER)	\
	CASESTATE(USTATE_DURATION)	\
	CASESTATE(USTATE_COMBIN_STONE_PET)	\
	CASESTATE(USTATE_COMBIN_BONE_PET)	\
	CASESTATE(USTATE_COMBIN_GOD_FIGHTER)	\
	CASESTATE(USTATE_FIREWALL)	\
	CASESTATE(USTATE_COMBIN_WIND_PET)	\
	CASESTATE(USTATE_KEEP_FAR_AWAY)	\
	CASESTATE(USTATE_EAT_GHOST)	\
	CASESTATE(USTATE_NO_FOOD_EAT)	\
	CASESTATE(USTATE_DEFENCE_RING)	\
	CASESTATE(USTATE_COMBIN_GOD_LEADER)	\
	CASESTATE(USTATE_DEFENCE_RING_EFFECT)	\
	CASESTATE(USTATE_STEEL_MAN_SKILL)	\
	CASESTATE(USTATE_STRENGTH_ATTACK_BLESS)	\
	CASESTATE(USTATE_TEAM_ATTACK_BIRD_FLAG)	\
	CASESTATE(USTATE_TEAM_ATTACK_FLOW_CLOUD)	\
	CASESTATE(USTATE_MOVE_FAST)	\
	CASESTATE(USTATE_CRAZY_ACTION)	\
	CASESTATE(USTATE_TECH_OF_WIND)	\
	CASESTATE(USTATE_ROTATE_FIRE_LAMP)	\
	CASESTATE(USTATE_COOL_TOUCH)	\
	CASESTATE(USTATE_PROTECT_CISHAN)	\
	CASESTATE(USTATE_DANCE_SHADOW)	\
	CASESTATE(USTATE_COMMON_TEMP_USE)	\
	CASESTATE(USTATE_STATIC_LIGHT_EFFECT)	\
	CASESTATE(USTATE_LIQUID_MOVE)	\
	CASESTATE(USTATE_STAND_WITH__GHOST)	\
	CASESTATE(USTATE_WEDDINGGIFT)	\
	CASESTATE(USTATE_COMBIN_IRON_PET)	\
	CASESTATE(USTATE_COMBIN_BONE_GUARD)	\
	CASESTATE(USTATE_COMBIN_XIAN_PET)	\
	CASESTATE(USTATE_TEAM_ATTACK_ONE_DIM)	\
	CASESTATE(USTATE_ULTRA_EQUIPMENT)	\
	CASESTATE(USTATE_REJECT_LIGHT_RING)	\
	CASESTATE(USTATE_TOGETHER_WITH_DRAGON)	\
	CASESTATE(USTATE_TOGETHER_WITH_TIGER)	\
	CASESTATE(USTATE_HIDE_PET_TRAINING)	\
	CASESTATE(USTATE_ATTACK_BLESS)	\
	CASESTATE(USTATE_GOD_LABOR_BLESS)	\
	CASESTATE(USTATE_HIDE_NOMOVE_STATE)	\
	CASESTATE(USTATE_PRIVATE_STORE)	\
	CASESTATE(USTATE_XIXINGEMIA)	\
	CASESTATE(USTATE_HORSE_GLOW)	\
	CASESTATE(USTATE_COMBIN_FIRE_LEADER)	\
	CASESTATE(USTATE_COMBIN_SIX_GHOST)	\
	CASESTATE(USTATE_COMBIN_THREE_DIM)	\
	CASESTATE(USTATE_CHONGFENG)	\
	CASESTATE(USTATE_QHCHONGFENG)	\
	CASESTATE(USTATE_COUNTRY_GUARD)	\
	CASESTATE(USTATE_STILL)	\
	CASESTATE(USTATE_BIKECONFUSION)	\
	CASESTATE(USTATE_SPEEDUP)	\
	CASESTATE(USTATE_BIKE_BLIND)	\
	CASESTATE(USTATE_HORSEFASHION_FOOT1)	\
	CASESTATE(USTATE_TRIP)	\
	CASESTATE(USTATE_STRAY)	\
	CASESTATE(USTATE_BIKERACE)	\
	CASESTATE(USTATE_GOD)	\
	CASESTATE(USTATE_GOTO)	\
	CASESTATE(USTATE_TIANXIADIYI)	\
	CASESTATE(USTATE_TIANXIADIYI2)	\
	CASESTATE(USTATE_SHENQI)	\
	CASESTATE(USTATE_ZHANQI) \
	CASESTATE(USTATE_ZHANLINGTUTENG) \
	CASESTATE(USTATE_WANGLING)	\
	CASESTATE(USTATE_TIANSHEN)	\
	CASESTATE(USTATE_ZIRAN)		\
	CASESTATE(USTATE_WUFANGJIANG)	\
	CASESTATE(USTATE_MOFAKONGJV)	\
	CASESTATE(USTATE_TIANLONG)	\
	CASESTATE(USTATE_DADI)	\
	CASESTATE(USTATE_WANGZHE)	\
	CASESTATE(USTATE_SHIXUEKUANGGONG)	\
	CASESTATE(USTATE_WUMO)	\
	CASESTATE(USTATE_HUANMAN)	\
	CASESTATE(USTATE_WANJIEDIYU)	\
	CASESTATE(USTATE_MOWU)	\
	CASESTATE(USTATE_HUOYANJIANSHE)	\
	CASESTATE(USTATE_LUOMA)	\
	CASESTATE(USTATE_RENWOYOU)	\
	CASESTATE(USTATE_PHOTO)	\
	CASESTATE(USTATE_JIANYUHURT)	\
	CASESTATE(USTATE_FLOWER_1)	\
	CASESTATE(USTATE_FLOWER_2)	\
	CASESTATE(USTATE_FLOWER_3)	\
	CASESTATE(USTATE_FLOWER_TODAY_1)	\
	CASESTATE(USTATE_FLOWER_TODAY_2)	\
	CASESTATE(USTATE_FLOWER_TODAY_3)	\
	CASESTATE(USTATE_FLOWER_YESTODAY_1)	\
	CASESTATE(USTATE_DANCE)	\
	CASESTATE(USTATE_IS_TANGYI) \
	CASESTATE(USTATE_BLOG) \
	CASESTATE(USTATE_HAIZHANZHANLING)	\
	CASESTATE(USTATE_YUNXUAN2)	\
	CASESTATE(USTATE_BIANMUZHUANG)	\
	CASESTATE(USTATE_MAIFU)	\
	CASESTATE(USTATE_KANGCHONGFENG)	\
	CASESTATE(USTATE_SHANBISHANGSHENG)	\
	CASESTATE(USTATE_HUSHISHANBI)	\
	CASESTATE(USTATE_ELING)	\
	CASESTATE(USTATE_BIAOJI)	\
	CASESTATE(USTATE_MADU)	\
	CASESTATE(USTATE_SHUFU)	\
	CASESTATE(USTATE_MIHUO)	\
	CASESTATE(USTATE_JIANZHONGJI)	\
	CASESTATE(USTATE_ZHONGGU)	\
	CASESTATE(USTATE_MAJING)	\
	CASESTATE(USTATE_SHUFUYI)	\
	CASESTATE(USTATE_MIHUOYI)	\
	CASESTATE(USTATE_JIANZHONGJIYI)\
	CASESTATE(USTATE_MEINV)	\
	CASESTATE(USTATE_SHENZHU)	\
	CASESTATE(USTATE_MOZHU) \
	CASESTATE(USTATE_FLAG)	\
	CASESTATE(USTATE_QUANZIZHUANG1)	\
	CASESTATE(USTATE_QUANZIZHUANG2)	\
	CASESTATE(USTATE_QUANZIZHUANG) \
	CASESTATE(USTATE_TAIMIAOBAI) \
	CASESTATE(USTATE_TAIMIAOLAN) \
	CASESTATE(USTATE_TAIMIAOHUANG) \
	CASESTATE(USTATE_TAIMIAOLV) \
	CASESTATE(USTATE_TAIMIAOZI)\
	CASESTATE(USTATE_QUANZIZHUANG3)\
	CASESTATE(USTATE_FOOTMAGIC)\
	CASESTATE(USTATE_SECONDSOUL)\
	CASESTATE(USTATE_JUEDAISHUANGJIAO)\
	CASESTATE(USTATE_DAFUDAGUI)\
	CASESTATE(USTATE_NUQI)\
	CASESTATE(USTATE_XUERENZHUANGTAI) \
	CASESTATE(USTATE_MASK)\
	CASESTATE(USTATE_YAOPINJINGTONG)	\
	CASESTATE(USTATE_INSULT_KING_XURUO) \
	CASESTATE(USTATE_WINE_YESTERDAY_1)\
	CASESTATE(USTATE_WINE_HISTORY_1)\
	CASESTATE(USTATE_WINE_HISTORY_2)\
	CASESTATE(USTATE_JINGJIU)\
	CASESTATE(USTATE_JINGJIU_2)	\
	CASESTATE(USTATE_KING_AND_EMPEROR_PROTECT_FORBID)	\
	CASESTATE (USTATE_DIG_TREASURE)\
	CASESTATE(USTATE_OCCUPYGUARD)	\
	CASESTATE(USTATE_SHUANGGONGSHANGSHENG)	\
	CASESTATE(USTATE_SHUITUBUFU) \
	CASESTATE(USTATE_SHENGMINGSHANGSHENG) \
	CASESTATE(USTATE_BANQUET_GUEST)\
	CASESTATE(USTATE_YUNFU)\
	CASESTATE(USTATE_TOUYUN)\
	CASESTATE(USTATE_XINGDONGBUBIAN)\
	CASESTATE(USTATE_LOVE)\
	CASESTATE(USTATE_JINGJIE)\
	CASESTATE(USTATE_QIQIU1)\
	CASESTATE(USTATE_QIQIU2)\
	CASESTATE(USTATE_QIQIU3) \
	CASESTATE(USTATE_QIUQIAN)\
	CASESTATE(USTATE_DUNXIA)\
	CASESTATE(USTATE_LEYUAN)\
	CASESTATE(USTATE_CHANGMINGDENG1)\
	CASESTATE(USTATE_CHANGMINGDENG2)\
	CASESTATE(USTATE_CHANGMINGDENG3)\
	CASESTATE(USTATE_KUAILE_BAOBAO)\
	CASESTATE(USTATE_MEILI_BAOBAO)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_1)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_2)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_3)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_KILL_ROB)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_DOUBLE_ROB)\
	CASESTATE(USTATE_XKD_BLUE)\
	CASESTATE(USTATE_XKD_RED)\
	CASESTATE(USTATE_XKD_YELLOW)\
	CASESTATE(USTATE_HUANYING_HORSE_GLOW)\
	CASESTATE(USTATE_GLOSS_STONE)\
	CASESTATE(USTATE_DANCE_BALLOON1)\
	CASESTATE(USTATE_DANCE_BALLOON2)\
	CASESTATE(USTATE_DANCE_BALLOON3)\
	CASESTATE(USTATE_DANCE_BALLOON4)\
	CASESTATE(USTATE_DANCE_BALLOON5)\
	CASESTATE(USTATE_BLUE_ROSE1)\
	CASESTATE(USTATE_BLUE_ROSE2)\
	CASESTATE(USTATE_BLUE_ROSE3)\
	CASESTATE(USTATE_PKDAO_ZHANSHEN)\
	CASESTATE(USTATE_PKDAO_JIANQI)\
	CASESTATE(USTATE_PKDAO_QIANGXI)\
	CASESTATE(USTATE_QIANGGONG_GZ)\
	CASESTATE(USTATE_SUOXIAO)\
	CASESTATE(USTATE_FOOTPRINTS_1)\
	CASESTATE(USTATE_FOOTPRINTS_3)\
	CASESTATE(USTATE_FOOTPRINTS_5)\
	CASESTATE(USTATE_FOOTPRINTS_10)\
	CASESTATE(USTATE_JINGJIE1)\
	CASESTATE(USTATE_DRAGON_HERO)\
	CASESTATE(USTATE_TIMEGOD)\
    CASESTATE(USTATE_QUANZIZHUANG4)\
	CASESTATE(USTATE_JINGYANJIASU1)\
	CASESTATE(USTATE_DESERT_DEBUFF)\
	CASESTATE(USTATE_ZHOUNIAN_SUN_1)\
	CASESTATE(USTATE_ZHOUNIAN_SUN_2)\
	CASESTATE(USTATE_ZHOUNIAN_SUN_3)\
	CASESTATE(USTATE_ZHOUNIAN_SUN_4)\
	CASESTATE(USTATE_ZHOUNIAN_SUN_5)\
	CASESTATE(USTATE_CHANGMINGDENG4)\
	CASESTATE(USTATE_HORSE5STARSUIT)\
	CASESTATE(USTATE_HORSE8STARSUIT)\
	CASESTATE(USTATE_HORSE10STARSUIT)\
	CASESTATE(USTATE_HORSE12STARSUIT)\
	CASESTATE(USTATE_HORSE13STARSUIT)\
	CASESTATE(USTATE_PROTECT_ANGEL)\
	CASESTATE(USTATE_PROTECT_KNIGHT)\
	CASESTATE(USTATE_PROTECT_MESSENGER)\
	CASESTATE(USTATE_PROTECT_WIZARD)\
	CASESTATE(USTATE_OPEN_HOOP_WING)\
	CASESTATE(USTATE_GRASP_UNION_TOTEM)\
	CASESTATE(USTATE_QUANZIZHUANG5)\
	CASESTATE(USTATE_PK_GRADE_1)\
	CASESTATE(USTATE_PK_GRADE_2)\
	CASESTATE(USTATE_PK_GRADE_3)\
	CASESTATE(USTATE_PK_GRADE_4)\
	CASESTATE(USTATE_PK_GRADE_5)\
	CASESTATE(USTATE_PK_GRADE_6)\
	CASESTATE(USTATE_PK_GRADE_7)\
	CASESTATE(USTATE_PK_GRADE_8)\
	CASESTATE(USTATE_PK_GRADE_9)\
	CASESTATE(USTATE_HORSE_FACE_TIME)\
	CASESTATE(USTATE_CHANGMINGDENG5)\
	CASESTATE(USTATE_LABYRINTH_WHITE)\
	CASESTATE(USTATE_LABYRINTH_BLUE)\
	CASESTATE(USTATE_LABYRINTH_YELLOW)\
	CASESTATE(USTATE_LABYRINTH_GREEN)\
	CASESTATE(USTATE_LABYRINTH_PURPLE)\
	CASESTATE(USTATE_FASHIONEFFECT1)\
	CASESTATE(USTATE_FASHIONEFFECT2)\
	CASESTATE(USTATE_FASHIONEFFECT3)\
	CASESTATE(USTATE_FASHIONEFFECT4)\
	CASESTATE(USTATE_FASHIONEFFECT5)\
	CASESTATE(USTATE_JUNLINGTIANXIA)\
	CASESTATE(USTATE_YIDAIZONGSHI)\
	CASESTATE(USTATE_WEIZHENJIANGHU)\
	CASESTATE(USTATE_WEIFENGBAMIAN)\
	CASESTATE(USTATE_HPQIANGHUA)\
	CASESTATE(USTATE_QINGBAO_COLOR1)\
	CASESTATE(USTATE_QINGBAO_COLOR2)\
	CASESTATE(USTATE_QINGBAO_COLOR3)\
	CASESTATE(USTATE_QINGBAO_COLOR4)\
	CASESTATE(USTATE_QINGBAO_COLOR5)\
	CASESTATE(USTATE_UPGRADE_STAR)\
	CASESTATE(USTATE_WINE_BAIJIU)\
	CASESTATE(USTATE_WINE_MEIJIU)\
    CASESTATE(USTATE_WINE_HOUJIU)\
    CASESTATE(USTATE_WINE_QIONGJIU)\
    CASESTATE(USTATE_WINE_GONGJIU)\
    CASESTATE(USTATE_WINE_CHENJIU)\
	CASESTATE(USTATE_LABA_WHITE)\
	CASESTATE(USTATE_LABA_BLUE)\
	CASESTATE(USTATE_LABA_YELLOW)\
	CASESTATE(USTATE_LABA_GTEEN)\
	CASESTATE(USTATE_LABA_PURPLE)\
	CASESTATE(USTATE_MINEING_TRETURE)\
    CASESTATE(USTATE_PKGRADE_TEAM1)\
    CASESTATE(USTATE_PKGRADE_TEAM2)\
	CASESTATE(USTATE_MENGHUAN_LOVER)\
	CASESTATE(USTATE_COUNTRYWAROCCUPYTUTENG)\
	CASESTATE(USTATE_COUNTRYWAROCCUPYKINGFALG)\
	CASESTATE(USTATE_SAINTWAROCCUPYTUTENG)\
	CASESTATE(USTATE_SAINTWAROCCUPYSHENGTAN)\
	CASESTATE(USTATE_DRAGON_COLLECT)\
	CASESTATE(USTATE_OPEN_SHENGLING_WING)\
	CASESTATE(USTATE_HUANYING_HORSE_EFFECT1)\
	CASESTATE(USTATE_SUPER_MENGHUAN)\
	CASESTATE(USTATE_HIG_FANS_BLE)\
	CASESTATE(USTATE_MID_FANS_BLE)\
	CASESTATE(USTATE_LOW_FANS_BLE)\
	CASESTATE(USTATE_ACTIVE_BLE)\
	CASESTATE(USTATE_YUJIAO_DRAGON)\
	CASESTATE(USTATE_PIOUS_SOUL)\
	CASESTATE(USTATE_GUARDIAN_MARK)\
	CASESTATE(USTATE_QUANZIZHUANG6)\
	CASESTATE(USTATE_OPEN_SOULWING)\
	CASESTATE(USTATE_GOLD_BUSINESS)\
	CASESTATE(USTATE_GLOBALUNIONWARBLUEFLAG)\
	CASESTATE(USTATE_GLOBALUNIONWARBLUE)\
	CASESTATE(USTATE_GLOBALUNIONWARRED)\
	CASESTATE(USTATE_GLOBALUNIONWAROCCUPY)\
	CASESTATE(USTATE_GLOBALUNIONWARREDFLAG)\
	CASESTATE(USTATE_GLOBALUNIONWAR_HOLDBOX_SHENMI)\
	CASESTATE(USTATE_GLOBALUNIONWAR_HOLDBOX_ZHUFU)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_114)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_115)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_116)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_117)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_118)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_119)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_120)\
	CASESTATE(USTATE_GLOBALUNIONWAR_AFTER_USE_OBJ_121)\
	CASESTATE(USTATE_GLOBALUNIONWAR_GODOFWAR)\
	CASESTATE(USTATE_GLOBALUNIONWAR_POISONING)\
	CASESTATE(USTATE_SOULDANCE)\
	CASESTATE(USTATE_SHNOW_SHENQI_ANYWAY)\
	CASESTATE(USTATE_SHENQI_HAS_BEEN_FITED)\
	CASESTATE(USTATE_TANK_REPAIR)\
	CASESTATE(USTATE_WUSHEN_TIAN)\
	CASESTATE(USTATE_WUSHEN_DI)\
	CASESTATE(USTATE_WUSHEN_REN)\
	CASESTATE(USTATE_SUIT_CANGLONG)\
	CASESTATE(USTATE_SUIT_JULONG)\
	CASESTATE(USTATE_SUIT_LONGWANG)\
	CASESTATE(USTATE_GLOBALUNIONWAR_ZHAYAOBAO)\
	CASESTATE(USTATE_QIANGQI_QIANGSHU)\
        CASESTATE(USTATE_QIANGQI_QIANGHUN)\
        CASESTATE(USTATE_QIANGQI_HUADIWEILAO)\
        CASESTATE(USTATE_QIANGQI_GANZHI)\
        CASESTATE(USTATE_QIANGQI_XUANYUN)\
        CASESTATE(USTATE_QIANGQI_MINGJIEZHENGJIA)\
	CASESTATE(USTATE_QIANGQI_WUFANGZHENJIA)\
	CASESTATE(USTATE_QIANGQI_WUFANGGUANGHUAN)\
	CASESTATE(USTATE_QIANGQI_BIANSHEN)\
	CASESTATE(USTATE_GLOBALUNIONWAR_NO1)\
	CASESTATE(USTATE_GLOBALUNIONWAR_NO2To10)\
	CASESTATE(USTATE_BUDONGRUSHAN)\
	CASESTATE(USTATE_SHUANGZHI)\
	CASESTATE(USTATE_NEWZONE_BIG_REWARD)\
	CASESTATE(USTATE_TANK_ATK_BUF_VERIFY)\
	CASESTATE(USTATE_CHRISTTREECRAZY)\
	CASESTATE(USTATE_SUIT_GOD_CANGLONG)\
	CASESTATE(USTATE_SUIT_GOD_JULONG)\
	CASESTATE(USTATE_SUIT_GOD_LONGWANG)\
	CASESTATE(USTATE_FAIRY_NO_VISIT)\
	CASESTATE(USTATE_HEAD_TITLE_STATE)\
	CASESTATE(USTATE_TANK_ATKHPDEF_ONE)\
	CASESTATE(USTATE_SINGULARBEAUTY)\
	CASESTATE(USTATE_WEBLOGELF)\
	CASESTATE(USTATE_AUNIONWAR_DELIVE_RESOURCE)\
	CASESTATE(USTATE_QS_STATE_RED)\
	CASESTATE(USTATE_QS_STATE_GREEN)\
	CASESTATE(USTATE_NQS_HP_BUFF)\
	CASESTATE(USTATE_BOLL_HP_RED)\
	CASESTATE(USTATE_BOLL_HP_BLUE)\
	CASESTATE(USTATE_LOVE_CONTRACT_3)\
	CASESTATE(USTATE_LOVE_CONTRACT_5)\
	CASESTATE(USTATE_LOVE_CONTRACT_8)\
	CASESTATE(USTATE_CHARACTERFIGHTSOUL)\
	CASESTATE(USTATE_ALLYWAR_HOLD)\
	CASESTATE(USTATE_GRASS_BATTLE_NORMAL)\
	CASESTATE(USTATE_GRASS_BATTLE_POWER)\
	CASESTATE(USTATE_GRASS_ATTACK_BUFF)\
	CASESTATE(USTATE_BORN_BURNED)\
	CASESTATE(USTATE_BORN_BURNED_2)\
	CASESTATE(USTATE_GRASS_WHITE)\
	CASESTATE(USTATE_GRASS_BLUE)\
	CASESTATE(USTATE_GRASS_YELLOW)\
	CASESTATE(USTATE_GRASS_GREEN)\
	CASESTATE(USTATE_GRASS_PURPLE)\
	CASESTATE(USTATE_GRASS_BUFF)\
	CASESTATE(USTATE_ALLY_WAR_HERO)\
	CASESTATE(USTATE_GOlD_COMMANDER)\
	CASESTATE(USTATE_GET_MENGZHU)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON0)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON1)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON2)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON3)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON4)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON5)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON6)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON7)\
	CASESTATE(USTATE_FIGHT_SOUL_WEAPON8)\
	CASESTATE(USTATE_QUANZIZHUANG_15)\
	CASESTATE(USTATE_TULIP_9)\
	CASESTATE(USTATE_TULIP_99)\
	CASESTATE(USTATE_TULIP_999)\
	CASESTATE(USTATE_NEW_HORSE_REDUCE_STATE)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_4)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_5)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_6)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_7)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_8)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_9)\
	CASESTATE(USTATE_ZHENGTU_BATTLE_BRICK_10)\
	CASESTATE(USTATE_JIANGNAN_STYLE_DANCE)\
	CASESTATE(USTATE_JINLINLANG_DOWN_HP )\
	CASESTATE(USTATE_FREE_CONSUME_STATE)\
	CASESTATE(USTATE_GOOD_SHENGMA_EFFECT1)\
	CASESTATE(USTATE_GOOD_SHENGMA_EFFECT2)\
	CASESTATE(USTATE_GOOD_SHENGMA_EFFECT3)
#endif



/*
enum {
USTATE_DEATH  	= 0,//	死亡
USTATE_POISON  	= 1,//	中毒
USTATE_FREEZE  	= 2,//	冰冻
USTATE_LANDIFICATION = 3,//	冻结
USTATE_HIDE  	= 4,//	隐身
USTATE_TRADE  	= 5,//	交易
USTATE_WAR		= 6,//	交战状态
USTATE_LUCK  	= 7,//	幸运
USTATE_DECLINE  = 8,//	衰弱
USTATE_CRAZY  	= 9,//	狂热
USTATE_LUCKY  	= 10,//	祝福
USTATE_HEROLIST_NO  	= 11,//英雄排名前3名
USTATE_ARMOUR  	= 12,//	铁甲
USTATE_PRAY  	= 13,//	祈祷
USTATE_ZENGJIAHP_1 = 14,//帮会buff，80级下
USTATE_ZENGJIAMP_1 = 15,//家族buff，80下
USTATE_ZENGJIAHP_2 = 16,//帮会buff，80上
USTATE_ZENGJIAMP_2 = 17,//家族buff，80上
USTATE_BLIND  	= 18,//	失明
USTATE_ROCK		= 19,//	石化
USTATE_CONFUSION  	= 20,//	混乱
USTATE_PALSY  	= 21,//	麻痹
USTATE_BLED  	= 22,//	流血
USTATE_REVERT  	= 23,//	回复图腾
//USTATE_STILL			= 24, 	//定身
//USTATE_BIKECONFUSION		= 25,	//混乱
//USTATE_SPEEDUP			= 26, 	//加速
//USTATE_BIKE_BLIND      		= 27, 	//自行车大赛失明状态
//USTATE_TRIP			= 28,	//摔倒
//USTATE_STRAY			= 29,  	//找不着北
//USTATE_BIKERACE			= 30, 	//比赛状态
USTATE_RECOVERY         = 24,// 家族运镖
USTATE_LIFE     = 25,//healthy game
USTATE_PROCTECTED       = 26,// semi-healthy game
USTATE_ABILITY          = 27,// anti-healthy game
USTATE_BLOOD    = 28,// 吸血图腾
USTATE_MAGIC    = 29,// 法力图腾
USTATE_SLOW     = 30,// 缓慢图腾
USTATE_GAMEMSTER  	= 31,//	GM状态.
USTATE_DIGGING   	= 32,//	挖掘
USTATE_JINGYANDAN_1 = 33,//普通经验丹
USTATE_JINGYANDAN_2 = 34,//强化经验丹
USTATE_GATHERING        = 35,// 采集
USTATE_BUSINESSTASK		= 36,// 经营任务
USTATE_LZ_FANGHUDUN = 37,// 防护盾
USTATE_GUARD            = 38,// 护宝
USTATE_LZ_GAOSHEPAO = 39,// 高射炮
USTATE_TMTASK        = 40,// 太庙任务
USTATE_LZ_WUQI = 41,//	雾气
USTATE_LZ_XUANFENG = 42,//	旋风
USTATE_LZ_YULEI = 43,//	鱼雷
USTATE_SPEEDNESSATK	= 44,//	减速攻击
USTATE_LZ_RE = 45,//	热
USTATE_LZ_SHAYU = 46,//	鲨鱼追龙舟
USTATE_RELIVEWEAK	= 47,//   复活虚弱状态
USTATE_BOMB			= 48,//	诅咒炸弹
USTATE_RELIVERING	= 49,//	复活光环
USTATE_NOTHING		= 50,//	虚无
USTATE_MOREHURT		= 51,//	伤害加深
USTATE_LZ_MEIRENYU = 52,//	看到美人鱼
USTATE_OLD			= 53,//	衰老
USTATE_MINGYUN		= 54,//	命运
USTATE_MINDWEAK		= 55,//	智能削弱
USTATE_MAGICWEAK	= 56,//	法术削弱
USTATE_ROSE			= 57,//	玫瑰刺
USTATE_TOWER	= 58,//	上箭塔
USTATE_FACEOFF		= 59,//	易容术
USTATE_HURTWEAK		= 60,//	伤害减弱
USTATE_SIGNOFSNIPER	= 61,//	箭手标记
USTATE_GHOSTSHELL	= 62,		///	灵魂护盾
USTATE_ATKFAST		= 63,		///	攻击加速
USTATE_YUNBIAOQIANGHUA	= 64,		///	运镖强化
USTATE_KUAIMAJIABIAN	= 65,		///	快马加鞭
USTATE_TIANLUODIWANG	= 66,		///	天罗地网
USTATE_YUMASHU			= 67,		///	御马术
USTATE_MAPIXUNYANG		= 68,		///	马匹驯养
USTATE_QIANGSHENJIANTI	= 69,		///	强身健体
USTATE_YAOPINJINGTONG	= 70,		///	药品精通
USTATE_LILIANGJINGTONG	= 71,		///	力量精通
USTATE_ZHILIJINGTONG	= 72,		///	智力精通
USTATE_MINGJIEJINGTONG	= 73,		///	敏捷精通
USTATE_JINGSHENJINGTONG	= 74,		///	精神精通
USTATE_TIZHIJINGTONG	= 75,		///	体质精通
USTATE_SHANBIZUZHOU	= 76,		///	闪避诅咒
USTATE_START_QUEST	= 77,		///	任务开始
USTATE_DOING_QUEST	= 78,		///	任务进行中
USTATE_FINISH_QUEST	= 79,		///	任务完成
USTATE_TIZHIJIAQIANG	= 80,	///	体智加强
USTATE_RIDE			= 81,		///	骑马
USTATE_JIANZAOZHUANGTAI		= 82,		/// 辅助建造
USTATE_POWERDEF		= 83,		/// 防御强化
ZHANLINGZONGDUO 	= 84,		/// 占领帮会总舵
USTATE_LONGZHOUGUANGMANG = 85,		/// 龙舟光芒
USTATE_THREAT		= 86,		/// 恐吓
USTATE_ACCRTSKILL	= 87,		/// 精准之术
USTATE_DEATHHURT	= 88,		/// 致命一击
USTATE_SILENT		= 89,		/// 冷静
USTATE_HUNTERSIGN	= 90,		/// 猎手印记
USTATAE_CHUNQVDONGLAI = 91,		/// 春去冬来
USTATE_PROTECTGOODS	= 92,		/// 护宝
USTATE_MAGICVESSEL	= 93,		/// 法力容器
USTATE_POWERBASE	= 94,		/// 元神增强
USTATE_BREAKBASE	= 95,		/// 元神分裂
USTATE_CHANGEFACE	= 96,		/// 易容术
USTATE_RUSHCRAZY	= 97,		/// 冲锋晕眩
USTATE_DIAMONDMAGIC	= 98,		/// 金刚法咒
USTATE_UPMAGIC		= 99,		/// 升华法咒
USTATE_GODBLESS		= 100,		/// 神圣祝福
USTATE_ZIZHUANG		= 101,		/// 紫装
USTATE_LOSTSPRITE	= 102,		/// 晕眩
USTATE_BLOODATTACK	= 103,		/// 血爪攻击
USTATE_ARROWCONTROL = 104,		/// 弓箭掌握
USTATE_SITDOWN		= 105,		/// 坐下
USTATE_SUMMON_STRENGTH	= 106, //召唤兽强化
USTATE_DEFENCE_HURT		= 107, //高速闪避
USTATE_HURT_ABSTRACT	= 108, //伤害吸收
USTATE_BOMB_ATTACK		= 109, //爆击
USTATE_MAGIC_DEFENCE	= 110, //魔盾术
USTATE_FIRST_AID		= 111, //治疗术
USTATE_ANGRY			= 112, //愤怒
USTATE_PK               = 113, //PK追加状态
USTATE_SAY_NOTHING		= 114, //胡言乱语
USTATE_WIND_ATTACK		= 115, //狂风决
USTATE_FIRE_ATTACK		= 116, //灼伤
USTATE_PET_CARE			= 117,
USTATE_SPECIAL_DEFENCE	= 118,
USTATE_BREAK_DEFENCE	= 119,
USTATE_WEIGHT_HURT		= 120,
USTATE_RED_FIRE_JUE		= 121,
USTATE_MOST_BEST_DEFENCE	= 122,
USTATE_TAKE_CARE		= 123,
USTATE_GIVEUP_MACHINE	= 124,
USTATE_MOST_BEST_GOLD_DEFENCE	= 125,
USTATE_FIRE_WALL_DEFENCE	= 126,
USTATE_ICE_EQUIPMENT		= 127,
USTATE_ICE_FIGHT		= 128,
USTATE_ICE_DEFENCE		= 129,
USTATE_HIDEN_SOUND		= 130,
USTATE_GOD_GIVE_SOUND	= 131,
USTATE_CONJIONCE_TOGETHER	= 132,
USTATE_ROCK_STATE		= 133,
USTATE_WIND_SKILL		= 134,
USTATE_BAD_SAY			= 135,
USTATE_EAT_EAGLE		= 136,
USTATE_EAT_SOUL			= 137,
USTATE_POISON_EQUIPMENT	= 138,
USTATE_FIGHT_TO_DEFENCE	= 139,
USTATE_DEFENCE_TO_FIGHT	= 140,
USTATE_CAREFUL_LOOKAT	= 141,
USTATE_GOLD_EQUIPMENT	= 142,
USTATE_MAGIC_EQUIPMENT	= 143,
USTATE_IRON_EQUIPMENT	= 144,
USTATE_ATTACK_INCREASE	= 145,
USTATE_DEFENCE_INCREASE	= 146,
USTATE_FIRE_BURNING	= 147,
USTATE_BOW_ARROW_SKILL	= 148,
USTATE_MAGIC_SKILL	= 149,
USTATE_SPRITE_SKILL	= 150,
USTATE_GUNSHU_SKILL	= 151,
USTATE_MAGIC_SKILL_MASTER	= 152,
USTATE_DURATION	= 153,
USTATE_COMBIN_STONE_PET	= 154,
USTATE_COMBIN_BONE_PET	= 155,
USTATE_COMBIN_GOD_FIGHTER	= 156,
USTATE_RELIVE_PET		= 157,
USTATE_GOD_BLESS		= 158,
USTATE_DEFENCE_LOWER	= 159,
USTATE_CUT_SOFTBONE		= 160,
USTATE_FEEDIN_OBJ		= 161,
USTATE_FAMILY_ADD_PATK	= 162,
USTATE_FAMILY_ADD_MATK	= 163,
USTATE_FAMILY_ADD_PDEF	= 164,
USTATE_FAMILY_ADD_MDEF	= 165,
USTATE_FAMILY_ADD_MAXHP	= 166,
USTATE_FAMILY_ADD_MAXMP	= 167,
USTATE_COUNTRY_WAR	= 168, // 国战状态(当对方与自己处于国战状态时，发送这个标志)
USTATE_FIREWALL			= 169,
USTATE_FEED_BLOOD		= 170,
USTATE_SAY_ANGRY		= 171,
USTATE_NEED_NOT_FACE	= 172,
USTATE_MOVE_POS_SPEED	= 173,
USTATE_STAND_SOLID		= 174,
USTATE_SHAKE_ATTACK		= 175,
USTATE_BLOOD_ANGRY		= 176,
USTATE_KEEP_SILENCE		= 177,
USTATE_BOTH_SKILL_IN_MIND	= 178,
USTATE_SAY_BAD_WORDS	= 179,
USTATE_COMBIN_WIND_PET	= 180,
USTATE_KEEP_FAR_AWAY	= 181,
USTATE_COLD_ICE_SKILL	= 182,
USTATE_FAST_SHOOT		= 183,
USTATE_EAT_GHOST		= 184,
USTATE_NO_FOOD_EAT		= 185,
USTATE_DEFENCE_RING		= 186,
USTATE_COMBIN_GOD_LEADER	= 187,
USTATE_SOFT_CLOTH		= 188,
USTATE_GIVEUP_LIFE		= 189,
USTATE_TWO_COLD_EFFECT	= 190,
USTATE_DEFENCE_RING_EFFECT	= 191,
USTATE_STEEL_MAN_SKILL	= 192,
USTATE_NO_COUNTRY_LIMIT	= 193,
USTATE_STRENGTH_ATTACK_BLESS	= 194,
USTATE_TEAM_ATTACK_BIRD_FLAG	= 195,
USTATE_TEAM_ATTACK_FLOW_CLOUD	= 196,
USTATE_NO_MOVE			= 197,
USTATE_MOVE_FAST		= 198,
USTATE_GOD_BLESS_U		= 199,
USTATE_FIRE_ROAD		= 200,
USTATE_CRAZY_ACTION		= 201,
USTATE_KILL_MAGIC_DEFENCE	= 202,
USTATE_KILL_PHYSIC_DEFENCE	= 203,
USTATE_TECH_OF_WIND		= 204,
USTATE_UNLIMIT_MAGIC	= 205,
USTATE_GOD_FIGHTER_EYE	= 206,
USTATE_ROTATE_FIRE_LAMP	= 207,
USTATE_COOL_TOUCH		= 208,
USTATE_DANCE_SHADOW		= 209,
USTATE_WIND_THOUNDER_DEFENCE	= 210,
USTATE_COMMON_TEMP_USE	= 211,
USTATE_ICE_BOX_PROTECT	= 212,
USTATE_STATIC_LIGHT_EFFECT	= 213,
USTATE_SOFT_ATTACK		= 214,
USTATE_MAGIC_DEFENCE_SWORD	= 215,
USTATE_LIQUID_MOVE		= 216,
USTATE_MP_STRENGTH		= 217,
USTATE_HP_STRENGTH		= 218,
USTATE_ATTACK_BACK_HEART = 219,
USTATE_SOFT_BOTH_HAND	= 220,
USTATE_FIRE_HEART_SKILL	= 221,
USTATE_CRAZY_ATTACK		= 222,
USTATE_IGNORE_ATTACK	= 223,
USTATE_STAND_WITH__GHOST	= 224,
USTATE_LION_HEART		= 225,
USTATE_WIND_LEADER		= 226,
USTATE_COMBIN_IRON_PET	= 227,
USTATE_COMBIN_BONE_GUARD	= 228,
USTATE_COMBIN_XIAN_PET		= 229,
USTATE_RESCUE_QUICKLY	= 230,
USTATE_NO_USE_SKILL		= 231,
USTATE_ICE_RANGE		= 232,
USTATE_PROTECT_SKILL	= 233,
USTATE_TEAM_ATTACK_ONE_DIM	= 234,
USTATE_ULTRA_EQUIPMENT	= 235,
USTATE_FIRE_EAT_ALL		= 236,
USTATE_REJECT_LIGHT_RING	= 237,
USTATE_SOFT_LOVE_HEART	= 238,
USTATE_TOGETHER_WITH_DRAGON	= 239, // 龙精附体
USTATE_TOGETHER_WITH_TIGER	= 240, // 虎魄附体
USTATE_IRON_BONE_SPRITE		= 241,
USTATE_IRON_BONE_GUARD		= 242,
USTATE_BEFORE_DIE_STATE		= 243,
USTATE_DO_WITHOUT_THINKING	= 244,
USTATE_HIDE_PET_TRAINING	= 245,
USTATE_RELIVE_FAST_STATE	= 246,
USTATE_ATTACK_BACK_STATE	= 247,
USTATE_FIRE_WITH_FIRE		= 248,
USTATE_FIRE_NO_EFFECT		= 249,
USTATE_ATTACK_BLESS		= 250,
USTATE_GOD_LABOR_BLESS		= 251,
USTATE_STRENGTH_DEFENCE_SKILL	= 252,
USTATE_HIDE_NOMOVE_STATE	= 253,
USTATE_PRIVATE_STORE		= 254, // 摆摊
USTATE_HANLIU			= 255,//寒流
USTATE_XIXINGEMIA		= 256,//洗心革面
USTATE_HORSE_GLOW      = 257,       //马匹发光
USTATE_BLIND_STRENGTH	= 258,
USTATE_MAKE_FORWORD		= 259,
USTATE_COME_ON_BABY		= 260,
USTATE_ATTACK_STORM_SKILL	= 261,
USTATE_PROPERTY_DROPDOWN	= 262,
USTATE_HEART_OF_DEAMON		= 263,
USTATE_BODY_COLD_STONE		= 264,
USTATE_BODY_CHANGE_OLD		= 265,
USTATE_SHAINT_SHIELD_BLESS	= 266,
USTATE_SHAINT_LIGHT_BLESS	= 267,
USTATE_GIVEUP_BACK_ROAD		= 268,
USTATE_PEOPLE_CAN_DEFEAT_GOD	= 269,
USTATE_WASH_SNOW_LIGHT_RING	= 270,
USTATE_COMBIN_FIRE_LEADER	= 271,
USTATE_COMBIN_SIX_GHOST		= 272,
USTATE_COMBIN_THREE_DIM		= 273,
USTATE_HURT_XIAN		= 274,
USTATE_HURT_MAGIC		= 275,
USTATE_DEATH_ATTACH		= 276,
USTATE_POWER_SPRITE		= 277,
USTATE_CALL_RAIN		= 278,
USTATE_DEEP_EARTH_FIRE		= 279,
USTATE_BLOOD_DUTY		= 280,
USTATE_DANCE_AMONG_DURT_WATER	= 281,
USTATE_DAOJISHI			= 282,//在收费地图的计时
USTATE_DIWANGDAO		= 283,	
USTATE_SHIZIHOU			= 284,
USTATE_XIXUE_P			= 285,
USTATE_FANGYUHUAN_P		= 286,
USTATE_HUIFUHUAN_P		= 287,
USTATE_NINGJIE			= 288,
USTATE_FANSHEGH_P		= 289,
USTATE_QIANGGONGZHUFU_P		= 290,
USTATE_SHENNONGHUYOU_P		= 291,  // 神农护佑
USTATE_SHENLONGITEM		= 292,  //龙王神力
USTATE_ZHUFUSHUIITEM		= 293,  //祝福水
USTATE_QIFUSHUIITEM		= 294,  //祈福水
USTATE_SHENGSHUIITEM		= 295,  //圣水
USTATE_WUDUSANITEM		= 296,  //五毒散
USTATE_BANBUDIEITEM		= 297,  //含笑半步颠
USTATE_DUANHUNSANITEM		= 298,  //断魂散
USTATE_SANGMINGSANITEM		= 299,  //丧命散
USTATE_MIQINGSANITEM		= 300,  //迷情散
USTATE_LIUYUNZHEN_P             = 301,  // 流云阵状态
USTATE_EXP	   = 302,		//   1.5倍经验状态
USTATE_EXP1	   = 303,		//   1.25倍经验状态
USTATE_EXP2	   = 304,		//   1.75倍经验状态
USTATE_TANK_HP			= 317,  //生命战车状态
USTATE_TANK_ATK			= 318,  //攻击战车状态
USTATE_TANK_DEF			= 319,  //防御战车状态
USTATE_COUNTRY_GUARD	= 320,  // 国运状态
USTATE_SHENGMINGFALIZFS_1       = 321,  //天之祝福石BUFFER
USTATE_SHENGMINGFALIZFS_2       = 322,  //强化天之祝福石BUFFER
USTATE_MOGONGZFS_1              = 323,  //地之祝福石
USTATE_MOGONGZFS_2              = 324,  //强化地之祝福石
USTATE_WUGONGZFS_1              = 325,  //人之祝福石
USTATE_WUGONGZFS_2              = 326,  //强化人之祝福石
USTATE_STILL			= 327, 	//定身
USTATE_BIKECONFUSION		= 328,	//混乱
USTATE_SPEEDUP			= 329, 	//加速
USTATE_BIKE_BLIND      		= 330, 	//自行车大赛失明状态
USTATE_TRIP			= 331,	//摔倒
USTATE_STRAY			= 332, 	//找不着北
USTATE_BIKERACE			= 333, 	//比赛状态
USTATE_GOD			= 334, 	//比赛状态
USTATE_GOTO			= 335, 	//比赛状态
MAX_STATE = 336                 /// 最大状态数
};

*/
